export const RegistrationSelectors = {
  genderRadio: '[#id-gender1]',
  passwordRegistrationInput: '[data-qa="password"]',
  birthDaySelect: '[data-qa="days"]',
  birthMonthSelect: '[data-qa="months"]',
  birthYearSelect: '[data-qa="years"]',
    firstNameInput: '[data-qa="first_name"]',
    lastNameInput: '[data-qa="last_name"]',
    companyInput: '[data-qa="company"]',
    address1Input: '[data-qa="address"]',
    address2Input: '[data-qa="address2"]',
    countrySelect: '[data-qa="country"]',
    stateInput: '[data-qa="state"]',
    cityInput: '[data-qa="city"]',
    zipCodeInput: '[data-qa="zipcode"]',
    mobileNumberInput: '[data-qa="mobile_number"]',
    createAccountButton: '[data-qa="create-account"]',
    continueButton: '[data-qa="continue-button"]',
};
